### ISSUE TITLE
My name has only 1 't'

### ISSUE THREAD

**Issue by matesitox** [DataWorkz-NL/dataworkz-site#1]
https://datanew.kokkelaar.nl/team/

![image](https://user-images.githubusercontent.com/1717667/92114485-30367d00-edf1-11ea-8449-5c53ba9c87dc.png)

"Matthijs" should be "Mathijs"

**Comment by jkokkeler** [comment]
Extra is niet beter?

**Comment by matesitox** [comment]
No I'm a coffee person.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jkokkeler** [comment]
Is gefixed, in de nieuwe versie staat het online
