### ISSUE TITLE
Eerste regel tekst 'big' weglaten

### ISSUE THREAD

**Issue by TjianL** [DataWorkz-NL/dataworkz-site#13]
Momenteel is de slogan:

`Maatwerk oplossingen voor uw big data vraagstukken`

Voorstel is om 'big' uit de slogan te halen:

`Maatwerk oplossingen voor uw data vraagstukken`

Small data vraagstukken doen we ook :D

**Comment by jkokkeler** [comment]
Done, wordt aangepast
