### ISSUE TITLE
Embedded slide show van 'Team' weer terug op de front page

### ISSUE THREAD

**Issue by TjianL** [DataWorkz-NL/dataworkz-site#14]
Het allersterkste wat ik vond van onze huidige/oude website was de embedded slideshow van momenteel deze pagina:
https://datanew.kokkelaar.nl/team/

Nu is deze pagina een beetje verstopt. Voorstel is om de embedded slideshow terug te halen en een prominente plek te geven op de frontpage. Misschien onder het kopje 'Over Dataworkz'

**Comment by jkokkeler** [comment]
Had wel een voorstel gedaan voor een slideshow, is er helaas niet door heen gekomen. Hoe lager hij op de voorpagina komt, hoe minder mensen er naar kijken. 

Wat voegt een slideshow toe? zie http://shouldiuseacarousel.com
