### ISSUE TITLE
Popup in plaats van nieuwe pagina bij https://datanew.kokkelaar.nl/team/

### ISSUE THREAD

**Issue by TjianL** [DataWorkz-NL/dataworkz-site#15]
Gerelateerd aan: https://github.com/DataWorkz-NL/dataworkz-site/issues/14

Momenteel kom je op een nieuwe pagina terecht als je klikt op een persoon bij: https://datanew.kokkelaar.nl/team/

Voorstel is om (net als vroegah) een popup te krijgen van de informatie in plaats naar een nieuwe pagina te gaan. Dat maakt het browsen door verschillende personen heen veel makkelijker (en zullen bezoekers dat sneller doen).

**Comment by jkokkeler** [comment]
bleh nee

**Comment by jkokkeler** [comment]
Er staat nu meer dan alleen een foto en beschrijving van de foto erbij, er staat nu ook de workshops en blogs van mensen bij, dan is een popup niet handig.
