### ISSUE TITLE
Fresh pageload on firefox at high-res (2560x1440) produces wrong layout on team page

### ISSUE THREAD

**Issue by matesitox** [DataWorkz-NL/dataworkz-site#2]
https://datanew.kokkelaar.nl/team/

![image](https://user-images.githubusercontent.com/1717667/92115030-19dcf100-edf2-11ea-8982-151d704bd843.png)

same page load on half my screen gives correct results:

![image](https://user-images.githubusercontent.com/1717667/92115334-8f48c180-edf2-11ea-9300-e397a789db7c.png)

**Comment by jkokkeler** [comment]
Goeie van de resolutie, hij doet het alleen met een boven 'groot' verhouding. Ik ga er naar kijken of ik een refresh kan inbouwen of de lib ervan updaten.

**Comment by jkokkeler** [comment]
Lib is geupdate, met de nieuwe versie zie je wel een groot verschil in performance, komt met de nieuwe versie.
