### ISSUE TITLE
laden zonder caching duurt lang

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#22]
De eerste keer laden duurt erg lang. rond 10 seconden. Is er iets aan te optimeren? 
Maar misschien is dit ook allen omdat er iets moet worden precompileert? Ken ik nog van servlets ;-)
Even kijken hoe dit gaat als iemand geen lokale cache gebruikt, maar de pagina door een ander wel al eerder is opgeroepen.

**Comment by jkokkeler** [comment]
Iets met png's die 2,4mb zijn ;) heb ze geresized en naar jpg gezet en nu is die wel wat sneller ;) 

Moeten we wel wat voor verzinnen hoe dat automatisch gaat

**Comment by martsky** [comment]
hahahaha, goede!

Groetjes,
Martin

Sent from my iPhone, trading speed for typos
----------------------------
marwei0@gmail.com
