### ISSUE TITLE
cosmetical: alignment Oplossingen

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#3]
is it possible to somehow get all three items (Data Oplossingen, ...) in one row? Op de linke kant is nu een breed wit vlak, daar zou het op zich nog moeten inpassen. 

![Screen Shot 2020-09-14 at 09 49 55](https://user-images.githubusercontent.com/2651453/93058417-aa77c480-f66f-11ea-8f84-5b2220ff91fd.png)

**Comment by martsky** [comment]
Misschien is het een idee om elk item op een eigen regel te plakken
En dan in de zelfde regel even kort de titels van de items te noemen (i.e. no more messy data, CD4ML, ...) en klanten dan op elk item kunnen klikken naar een pagina, die meer info geeft (https://datanew.kokkelaar.nl/solutions/#data-oplossingen)


![image](https://user-images.githubusercontent.com/2651453/93065836-7e614100-f679-11ea-9fce-9a14f682f837.png)

**Comment by jkokkeler** [comment]
Alles in 1 rij kan denk ik wel, maar dan wordt het op kleine schermen onder elkaar.

Denk dat het wel beter is om de verdieping op de onderliggende pagina's te houden.

**Comment by jkokkeler** [comment]
Staat in 1 rij
