### ISSUE TITLE
workshops dubbeld

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#4]
Workshops staan op de voorpagina nu dubbeld en leiden naar verschillende pagina's. "Onze workshops" kan weg.

**Comment by jkokkeler** [comment]
Hoe bedoel je dubbel?

En elke verschillende pagina's bedoel je? elke workshop heeft zijn eigen pagina zoals afgesproken

Waarom kan "onze workshops"  weg? het is toch goed om dit te etaleren op de voorpagina?

**Comment by jkokkeler** [comment]
opgelost
