### ISSUE TITLE
pagina Data Oplossingen

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#5]
1) "Quickwins" is een algemeen toelichting op data oplossingen. Nu lijkt het layout technisch alsof het een net zo een item is als No more messy data. Als je Het textje onder "Quickwins" op de Home> Data Oplossingen zet, is het volgens mij opgelost.  

2) No more messy data: Hier zal ik graag de hele text van de flyer willen zien. En idealiter ook een stukje van de layout van de flyer (i.e. de kostenpyramide) ook tonen. 

3) Ook voor CD4ML komt er dadelijk een flyer en dus meer text en een afbeelding. Als dit voor nog meer items Is het mogelijk om aparte pagina's te maken voor elk submenu item. Dus Oplossingen op een eigen pagina, Consulting op een eigen pagina en Workshops op een eigen pagina? 

4) Ik mis een menu link van de home pagina naar "Data Oplossingen". Ik zou het item "Workshops" vervangen door Oplossingen met een submenu met 3 items (Quickwins, Consulting, Workshops). Kan dat? 

5) Workshops staan er dubbeld op.

**Comment by jkokkeler** [comment]
1. zal ik aanpassen, moet even kijken hoe dat gaat komen met de nieuwe layout

2. hele tekst ga ik niet doen, heb ik liever dat je verwijst naar een blog erover. Anders moet je namelijk ook bij de andere punten zo'n lap tekst er neer zetten. 

3. Geen eigen pagina's, gaat toch niemand naar door klikken. 

4. Kan wel, weet niet voor seo of het submenu een goed idee is, liever dus niet.

5. klopt maar de tekst over workshops is een intro text, de andere zijn echte doorkliks op de workshops zoals afgesproken. Of wil je die intro teksten weg en alleen de verwijzingen naar de workshops hebben staan?
