### ISSUE TITLE
kleine en grote letters bij elkaar

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#6]
![image](https://user-images.githubusercontent.com/2651453/93067195-33482d80-f67b-11ea-964b-df5b3093d27a.png)
In het menu staan alle items in capitals. Onderaan de pagina is dit mixed. HIer ook alles in capitals doen.

**Comment by jkokkeler** [comment]
Thnx, die moest ik nog aanpakken
