### ISSUE TITLE
menu/structuur

### ISSUE THREAD

**Issue by martsky** [DataWorkz-NL/dataworkz-site#7]
Ik zou volgende structuur voorstellen (zie website structuur.docx):

- HOME
- Solutions (N.B:of is SERVICES misschien beter?)
- - QUICKWINS
- - CONSULTING
- - WORKSHOPS
- INSIGHTS
- - EVENTS (kunnen we hier doorverwijzen ook naar oude events, zodat we geen lege pagina hebben)? 
- - BLOGS
- - GITHUB
- ABOUT
- - TEAM
- - TIMELINE
- - WERKEN BIJ
- CONTACT

Zodra we CASES hebben moeten we die ook opnemen in het menu tuissen SERVICES en INSIGHTS

**Comment by jkokkeler** [comment]
Te veel menu items, de suggestie die je geeft, geeft geen overzicht.

Max 4 items met sub menus graag

**Comment by jkokkeler** [comment]
Ah dit is een list... update je Markdown kennis ;), zal kijken wat ik kan doen maar dit zijn echt te links... en ook dat je aparte content wil... is allemaal weer extra werk en niemand gaat daar naar kijken...

Ik bel je morgen goed?

**Comment by jkokkeler** [comment]
Menu is klaar!
